# Linear Regression Module Documentation
MATH 533 Assignment 4

December 20th, 2024

Gulliver Hager, Evelyn Hubbard, Michael Montemurri

---
## models.py

This file provides examples and documentation for the key methods implemented in the `OLS`, `GLS`, and `Ridge` regression models. The examples illustrate how to use these methods, including fitting models, making predictions, and obtaining variance estimates.

### Class: OLS(include_intercept)
Ordinary Least Squares (OLS) regression model.
#### Initialization:
##### Parameters:
- **include_intercept** (`bool`): Whether the model includes an intercept term, default = true.
#### Methods:
##### `OLS.fit(X, y, use_gradient_descent=False, max_iter=1000, alpha=0.01, tol=1e-6)`
Fits the Ordinary Least Squares (OLS) model to the dataset.
###### Parameters:
- **X** (`numpy.ndarray` or `pandas.DataFrame`): Feature matrix of shape `(n_samples, n_features)`.
- **y** (`numpy.ndarray` or `pandas.Series`): Response vector of length `n_samples`.
- **use_gradient_descent** (`bool`, optional): Whether to use gradient descent for optimization (default: False).
- **max_iter** (`int`, optional): Maximum iterations for gradient descent (default: 1000).
- **alpha** (`float`, optional): Learning rate for gradient descent (default: 0.01).
- **tol** (`float`, optional): Convergence tolerance for gradient descent (default: 1e-6).
###### Returns:
None. Fits the model and stores coefficients in `self.beta`.

##### `OLS.predict(X)`
Predicts response values using the fitted OLS model.
###### Parameters:
- **X** (`numpy.ndarray` or `pandas.DataFrame`): Feature matrix of shape `(n_samples, n_features)`.
###### Returns:
- **predictions** (`numpy.ndarray`): Predicted values for each sample.

##### `OLS.estimate_variance(X, y)`
Estimates the variance-covariance matrix of the coefficients.
###### Parameters:
- **X** (`numpy.ndarray` or `pandas.DataFrame`): Feature matrix of shape `(n_samples, n_features)`.
- **y** (`numpy.ndarray` or `pandas.Series`): Response vector of length `n_samples`.
###### Returns:
- **variance_matrix** (`numpy.ndarray`): Variance-covariance matrix of the coefficients.

### Class: GLS(include_intercept)
Generalized Least Squares (GLS) regression model.
#### Initialization:
##### Parameters:
- **include_intercept** (`bool`): Whether the model includes an intercept term, default = true.
#### Methods:
##### `GLS.fit(X, y, sigma)`
Fits the Generalized Least Squares (GLS) model to the dataset.
###### Parameters:
- **X** (`numpy.ndarray` or `pandas.DataFrame`): Feature matrix of shape `(n_samples, n_features)`.
- **y** (`numpy.ndarray` or `pandas.Series`): Response vector of length `n_samples`.
- **sigma** (`numpy.ndarray`): Covariance matrix of the errors.
###### Returns:
None. Fits the model and stores coefficients in `self.beta`.

### Class: Ridge(lambda, include_intercept)
Ridge regression model.
#### Initialization:
##### Parameters:
- **include_intercept** (`bool`): Whether the model includes an intercept term, default = true.
- **lambda** (`float`): $\lambda$ for the Ridge Estimator. 
#### Methods:
##### `Ridge.fit(X, y)`
Fits the Ridge regression model to the dataset.
###### Parameters:
- **X** (`numpy.ndarray` or `pandas.DataFrame`): Feature matrix of shape `(n_samples, n_features)`.
- **y** (`numpy.ndarray` or `pandas.Series`): Response vector of length `n_samples`.
###### Returns:
None. Fits the model and stores coefficients in `self.beta`.
##### `Ridge.estimate_variance(X, y)`
Estimates the variance-covariance matrix of the coefficients.
###### Parameters:
- **X** (`numpy.ndarray` or `pandas.DataFrame`): Feature matrix of shape `(n_samples, n_features)`.
- **y** (`numpy.ndarray` or `pandas.Series`): Response vector of length `n_samples`.
###### Returns:
- **variance_matrix** (`numpy.ndarray`): Variance-covariance matrix of the coefficients.

### Function: summary(model,X,y)
Generate a summary of the model's performance.
#### Parameters:
- **model** (`object`) : The regression model (OLS, GLS, or Ridge). Must have a `predict` method.
- **X** (`numpy.ndarray` or `pandas.DataFrame`): Feature matrix of shape `(n_samples, n_features)`.
- **y** (`numpy.ndarray` or `pandas.Series`): Response vector of length `n_samples`.

#### Returns
- A dictionary containing:
    - **coefficients** (`numpy.ndarray`): The fitted coefficients of the model.
    - **r_squared** (`float`): The R-squared value, representing the proportion of variance explained by the model.

---
## Example

Below is an example demonstrating the use of `OLS`, `GLS`, and `Ridge` regression models using synthetic datasets.


In [1]:
import numpy as np
import sys
sys.path.append('..')
from stats_module import *
import time


In [2]:
# Generate synthetic data
np.random.seed(0)
n_samples, n_features = 100, 5
X = np.random.randn(n_samples, n_features)
true_beta = np.random.randn(n_features)
y = X @ true_beta + np.random.normal(0, 0.5, n_samples)

# OLS Example
ols_model = OLS(include_intercept=True)
ols_model.fit(X, y)
ols_predictions = ols_model.predict(X)
ols_variance = ols_model.estimate_variance(X, y)
print("OLS Coefficients:", ols_model.beta)
print("OLS Variance Matrix:\n", ols_variance)

#get summary
ols_summary = summary(ols_model, X, y)
print("\nOLS Summary:")
print(f"beta_hat: {ols_summary['coefficients']}")
print(f"R-squared: {ols_summary['r_squared']}")

OLS Coefficients: [-0.14050914  0.31998031 -0.04676428  1.07625074 -0.2476699  -0.28304471]
OLS Variance Matrix:
 [[ 0.26947461  0.01435536  0.02568034 -0.02309508  0.03055034]
 [ 0.01435536  0.30429335  0.03317391 -0.01444322 -0.03871695]
 [ 0.02568034  0.03317391  0.27349674 -0.00615378 -0.0117382 ]
 [-0.02309508 -0.01444322 -0.00615378  0.25447581 -0.02888467]
 [ 0.03055034 -0.03871695 -0.0117382  -0.02888467  0.29307544]]

OLS Summary:
beta_hat: [-0.14050914  0.31998031 -0.04676428  1.07625074 -0.2476699  -0.28304471]
R-squared: 0.8405222067551491


In [3]:
# Now using the gradient descent method
gd_model = OLS(include_intercept=True)
gd_model.fit(X, y, use_gradient_descent=True, max_iter=1000, alpha=0.1, tol=1e-6)
gd_predictions = gd_model.predict(X)
gd_variance = gd_model.estimate_variance(X, y)
print("GD Coefficients:", gd_model.beta)

gd_summary = summary(gd_model, X, y)
print("\nGD Summary:")
print(f"beta_hat: {gd_summary['coefficients']}")
print(f"R-squared: {gd_summary['r_squared']}")

Converged after 37 iterations
GD Coefficients: [-0.14112852  0.31944985 -0.04772522  1.07540995 -0.24760737 -0.28247484]

GD Summary:
beta_hat: [-0.14112852  0.31944985 -0.04772522  1.07540995 -0.24760737 -0.28247484]
R-squared: 0.840521026564396


In [4]:
# GLS Example
sigma = np.diag(np.random.uniform(0.5, 1.5, size=n_samples))
gls_model = GLS(include_intercept=True)
gls_model.fit(X, y, sigma)
gls_predictions = gls_model.predict(X)
print("GLS Coefficients:", gls_model.beta)

gls_summary = summary(gls_model, X, y)
print("\nGLS Summary:")
print(f"beta_hat: {gls_summary['coefficients']}")
print(f"R-squared: {gls_summary['r_squared']}")

GLS Coefficients: [-0.16562031  0.30614536 -0.08014721  1.05472803 -0.23844273 -0.29863188]

GLS Summary:
beta_hat: [-0.16562031  0.30614536 -0.08014721  1.05472803 -0.23844273 -0.29863188]
R-squared: 0.8390183874062362


In [5]:
# We can see that this reduces to OLS when sigma is the identity matrix
gls_model = GLS(include_intercept=True)
gls_model.fit(X, y, np.eye(n_samples))
gls_predictions = gls_model.predict(X)
gls_variance = gls_model.estimate_variance(X, y)
print("GLS Coefficients:", gls_model.beta)
print("OLS Coefficients:", ols_model.beta)

GLS Coefficients: [-0.14050914  0.31998031 -0.04676428  1.07625074 -0.2476699  -0.28304471]
OLS Coefficients: [-0.14050914  0.31998031 -0.04676428  1.07625074 -0.2476699  -0.28304471]


In [6]:
# Ridge Example
ridge_model = Ridge(alpha=1.0, include_intercept=True)
ridge_model.fit(X, y)
ridge_variance = ridge_model.estimate_variance(X, y)
print("Ridge Coefficients:", ridge_model.beta)
print("Ridge Variance Matrix:\n", ridge_variance)

ridge_summary = summary(ridge_model, X, y)
print("\nRidge Summary:")
print(f"beta_hat: {ridge_summary['coefficients']}")
print(f"R-squared: {ridge_summary['r_squared']}")

Ridge Coefficients: [-0.14184602  0.31581555 -0.04829966  1.0648917  -0.24528437 -0.28000121]
Ridge Variance Matrix:
 [[ 0.26413765  0.01376477  0.02466189 -0.02213821  0.02933168]
 [ 0.01376477  0.29747623  0.03173532 -0.01390604 -0.03709305]
 [ 0.02466189  0.03173532  0.26803154 -0.00586855 -0.0112387 ]
 [-0.02213821 -0.01390604 -0.00586855  0.24975367 -0.02774526]
 [ 0.02933168 -0.03709305 -0.0112387  -0.02774526  0.28671054]]

Ridge Summary:
beta_hat: [-0.14184602  0.31581555 -0.04829966  1.0648917  -0.24528437 -0.28000121]
R-squared: 0.8404299157997424


In [7]:
# Now lets generate data with p > n and see how Ridge performs compared to OLS

# We can see that the variance estimates of the OLS are extremely large, indicating the solution is unstable
# Ridge on the other hand, provides a more stable solution.

n_samples, n_features = 20, 50
X = np.random.randn(n_samples, n_features)
true_beta = np.random.randn(n_features)
y = X @ true_beta + np.random.normal(0, 0.5, n_samples)

ols_model = OLS(include_intercept=True)
ols_model.fit(X, y)
ols_predictions = ols_model.predict(X)
ols_variance = ols_model.estimate_variance(X, y)
print("OLS Variance Diagonal:\n", np.diag(ols_variance))

ridge_model = Ridge(alpha=1.0, include_intercept=True)
ridge_model.fit(X, y)
ridge_variance = ridge_model.estimate_variance(X, y)
print("Ridge Variance Diagonal:\n", np.diag(ridge_variance))

# Compare summaries
ols_summary = summary(ols_model, X, y)
print("\nOLS Summary:")
print(f"beta_hat: {ols_summary['coefficients']}")
print(f"R-squared: {ols_summary['r_squared']}")
ridge_summary = summary(ridge_model, X, y)
print("\nRidge Summary:")
print(f"beta_hat: {ridge_summary['coefficients']}")
print(f"R-squared: {ridge_summary['r_squared']}")

OLS Variance Diagonal:
 [-1.00027051e+18 -4.11561002e+17 -8.83232400e+17 -2.91526426e+18
  1.45284392e+18  2.52272950e+17 -3.32767797e+18 -1.61982336e+18
  4.95819154e+17 -2.09801678e+17 -1.35443681e+18 -2.35029943e+18
  1.56118544e+18 -2.64321622e+18 -1.43048224e+18 -2.39659974e+16
  9.80690340e+17 -2.35302264e+18  2.51868425e+18 -7.42779700e+16
 -1.17279348e+18  3.84987422e+18  1.24361756e+18  2.15220374e+18
 -2.97372635e+17 -2.26337646e+18  6.35799974e+17 -3.05704482e+17
 -2.63055648e+18  1.03956358e+18 -1.06065915e+16  2.43532805e+18
 -2.33321652e+16  2.17650193e+17  1.30112746e+18 -3.17725861e+18
  5.21764722e+17  1.99748045e+17  2.71888113e+18  3.22311387e+18
  3.79642224e+15 -3.80678816e+18 -1.05509397e+18  5.81193890e+17
 -4.44989705e+17 -3.95919953e+18  2.36747029e+18  1.04849552e+18
 -1.00743896e+19 -1.42364082e+18]
Ridge Variance Diagonal:
 [-0.00387943 -0.00331424 -0.00574934 -0.0065698  -0.00235589 -0.0034576
 -0.00370803 -0.00471214 -0.00650786 -0.00539348 -0.00317097 -0.

In [8]:
# Now lets compare the time taken to fit the models with a large number of features

n_samples, n_features = 20000, 10000
X = np.random.randn(n_samples, n_features)
true_beta = np.random.randn(n_features)
y = X @ true_beta + np.random.normal(0, 0.5, n_samples)

start = time.time()
ols_model = OLS(include_intercept=True)
ols_model.fit(X, y)
ols_predictions = ols_model.predict(X)
end = time.time()
print("OLS Time:", end - start)


start = time.time()
gd_model = OLS(include_intercept=True)
gd_model.fit(X, y, use_gradient_descent=True, max_iter=1000, alpha=0.1, tol=1e-6)
gd_predictions = gd_model.predict(X)
end = time.time()
print("GD Time:", end - start)

OLS Time: 151.44079184532166
Converged after 336 iterations
GD Time: 67.34271597862244


## loss_estimation.py

This file provides functions to calculate different types of loss estimators for a given model over a dataset. These include the naive loss, training/testing loss, and leave-one-out loss estimators. The functions can be used with any model that implements the `fit()` and `predict()` methods.

##### `naive_loss_estimation(model, X, y)`
Calculates the naive loss estimator for a given model over a given dataset.

##### Parameters:
- **model** (`object`): The model for which the naive loss will be calculated. The model must have `fit()` and `predict()` methods implemented.
- **X** (`numpy.ndarray`): A 2D array of shape `(n_samples, n_features)` representing the feature set of the dataset.
- **y** (`numpy.ndarray`): A 1D array of length `n_samples` representing the true response values corresponding to the features in `X`.

##### Returns:
- **naive_loss_estimate** (`float`): The naive loss estimate, calculated as the mean squared error (MSE) between the true and predicted values.


##### `train_test_loss_estimation(model, X, y, train_range, test_range)`
This function calculates the training/testing loss estimator for a given model over a dataset, using a training set and a test set. The model is trained on the training set and evaluated on the test set. The loss is calculated as the Mean Squared Error (MSE) between the predicted and actual responses on the test set.

##### Parameters:
- **model** (`object`): The model for which the naive loss will be calculated. The model must have `fit()` and `predict()` methods implemented.
- **X** (`numpy.ndarray`): A 2D array of shape `(n_samples, n_features)` representing the feature set of the dataset.
- **y** (`numpy.ndarray`): A 1D array of length `n_samples` representing the true response values corresponding to the features in `X`.
- **train_range** (`list`): The list of indices which will be used to train the model.
- **test_range** (`list`): The list of indices which will the MSE of the trained model will be calculated on.

##### Returns:
- **train_test_loss_estimate** (`float`): The training-testing loss estimate, calculated as the mean squared error (MSE) between the true and predicted values over the testing data-set using the model trained on the training data set.



##### `loss_test_loss_estimation(model, X, y))`
Calculates the leave-one-out (LOO) loss estimator for a given model over a given dataset. Assumes that the model is a linear model and utilizes the known closed form solution for the LOO loss estimator for linear models for computational efficiency.

##### Parameters:
- **model** (`object`): The model for which the naive loss will be calculated. The model must have `fit()` and `predict()` methods implemented.
- **X** (`numpy.ndarray`): A 2D array of shape `(n_samples, n_features)` representing the feature set of the dataset.
- **y** (`numpy.ndarray`): A 1D array of length `n_samples` representing the true response values corresponding to the features in `X`.

##### Returns:
- **loo_loss_estimate** (`float`): The leave-one-out loss estimate, calculated using the closed form solution which is known for linear models.

---
### Example
Below is a code snippet where the three loss-estimations are used in practice for an OLS-estimator using a generated data set. In the first and second outputs we showcase that when given the entire data set for training and testing, the training-testing loss estimator reduces to the naive loss estimator. 

##### Generate data:
- For $n=1000$ samples and $p = 10$ covariates, generate design matrix X as standard normal data.
- Generate $y = X\beta + e$, where $\beta$ is given and $e$ is from a standard normal distribution.
....

In [9]:
np.random.seed(0)
n = 1000
p = 10
X = np.random.randn(n,p)
beta = np.arange(1,p+1)
e = np.random.randn(n)
y = X @  beta + e

model = OLS(include_intercept=True)
model.fit(X, y)

summ = summary(model, X,y)
print(f"beta_hat: {summ['coefficients']}")
print(f"R-squared: {summ['r_squared']}")


beta_hat: [0.05829502 0.95225026 1.9562936  3.05512177 3.97184667 5.06638368
 5.99138847 6.95918907 8.02403438 8.92732553 9.95198454]
R-squared: 0.9972319710008215


In [10]:
print("Naive:\t\t\t" +              str(naive_loss_estimation(model,X,y)))
print("Train-Test (full/full):\t" + str(train_test_loss_estimation(model, X, y, list(range(1,1000)), list(range(1,1000)) )))
print("Train-Test (half/half)):" +  str(train_test_loss_estimation(model, X, y, list(range(1,500)), list(range(500,1000)) )))
print("Leave-one-out:\t\t" +        str(loo_loss_estimation(model, X, y)))

Naive:			0.9807422146110315
Train-Test (full/full):	0.9816713360206676
Train-Test (half/half)):1.0587698658562517
Leave-one-out:		0.031690272476735934


## LinearModelTester.py

The file holds a class for performing hypothesis tests and building confidence intervals on a fitted gaussian homoscedastic linear model.

### Class: LinearModelTester(model)
#### Initialization:
##### Parameters:
- **model** (`object`): A fitted linear model object with:
    - **$\beta$** (`numpy.ndarray`): Estimated coefficients of the model.
    - **include_intercept** (`bool`): Whether the model includes an intercept term.
##### Raises:
- ValueError: If the model is not fitted (**\beta** is None).


#### Methods:
##### `hypothesis_t_test(X, y, null_hypothesis, alpha=0.05)`:
Perform a t-test for individual coefficients.
###### Parameters:
- **X** (`numpy.ndarray`): Feature matrix $(n x p)$.
- **y** (`numpy.ndarray`): Response vector $(n x 1)$.
- **null_hypothesis** (`numpy.ndarray`): Hypothesized values of coefficients.
- **$\alpha$** (`float`): Significance level (default 0.05).
###### Returns:
- List of dictionaries with:
    - **coefficient** (`int`): Index of the coefficient.
    - **beta_estimate** (`numpy.ndarray`): Estimated value.
    - **null_value** (`float`): Null hypothesis value for the coefficient.
    - **t_stat** (`float`): T-statistic.
    - **p_value** (`float`): P-value for t-statistic at significance level $\alpha$.
    - **reject_null** (`bool`): Whether the null hypothesis is rejected.

##### `hypothesis_F_test(X, y, R, r, alpha=0.05)`:
Perform an F-test for hypotheses of the form $R\beta = r$.
###### Parameters:
- **X** (`numpy.ndarray`): Feature matrix $(n x p)$.
- **y** (`numpy.ndarray`): Response vector $(n x 1)$.
- **R** (`numpy.ndarray`): Constraint matrix $(k x p)$.
- **r** (`numpy.ndarray`): Constraint vector $(k x 1)$.
- **$\alpha$** (`float`): Significance level (default 0.05).
###### Returns:
- Dictionary with:
    - **F_stat** (`float`): F-statistic.
    - **p_value** (`float`): P-value for F-statistic at significance level $\alpha$.
    - **reject_null** (`bool`): Whether the null hypothesis is rejected.

##### `confidence_interval(X, y, alpha=0.05)`:
Construct confidence intervals for model coefficients.
###### Parameters:
- **X** (`numpy.ndarray`): Feature matrix $(n x p)$.
- **y** (`numpy.ndarray`): Response vector $(n x 1)$.
- **$\alpha$** (`float`): Significance level (default 0.05).
###### Returns:
- List of dictionaries with:
    - **coefficient** (`int`): Index of the coefficient.
    - **beta_estimate** (`float`): Estimated value of the coefficient.
    - **confidence_lower** (`float`): Lower bound of the $1-\alpha$ confidence interval.
    - **confidence_upper** (`float`): Upper bound of the $1-\alpha$ confidence interval.

##### `prediction_interval_m(X, y, x_new, alpha=0.05)`:
Construct a confidence interval for $m(x_{new}) = x_{new}^\top\beta$ at a new point ($x_{new}$).
###### Parameters:
- **X** (`numpy.ndarray`): Feature matrix $(n x p)$.
- **y** (`numpy.ndarray`): Response vector $(n x 1)$.
- **x_new** (`numpy.ndarray`): New feature vector $(1 x p)$.
- **$\alpha$** (`float`): Significance level (default 0.05).
##### Returns:
- Dictionary with:
    - **mx_new_estimate** (`np.ndarray`): Estimated $m(x_{new})$.
    - **confidence_lower** (`float`): Lower bound of the $1-\alpha$ confidence interval.
    - **confidence_upper** (`float`): Upper bound of the $1-\alpha$ confidence interval.

##### `prediction_interval_y(X, y, x_new, alpha=0.05)`:
Construct a confidence interval for a new observation, $y_{new}$.
###### Parameters:
- **X** (`numpy.ndarray`): Feature matrix $(n x p)$.
- **y** (`numpy.ndarray`): Response vector $(n x 1)$.
- **x_new** (`numpy.ndarray`): New feature vector $(1 x p)$.
- **$\alpha$** (`float`): Significance level (default 0.05).
##### Returns
- Dictionary with:
    - **mx_new_estimate** (`np.ndarray`): Estimated $m(x_{new})$.
    - **confidence_lower** (`float`): Lower bound of the $1-\alpha$ confidence interval for $y_{new}$.
    - **confidence_upper** (`float`): Upper bound of the $1-\alpha$ confidence interval for $y_{new}$.

### Example:

In [11]:
#generate a random dataset
np.random.seed(0)
n = 1000
p = 5
X = np.random.randn(n,p)
beta = np.array([1,1,0,3,-1])
e = np.random.randn(n)
y = X @  beta + e

#fit an OLS estimator
model = OLS(include_intercept=True)
model.fit(X, y)

#generate new point to predict
x_new = np.random.randn(1, p)

summ = summary(model, X,y)
print(f"beta_hat: {summ['coefficients']}")
print(f"R-squared: {summ['r_squared']}")

beta_hat: [-0.02095641  0.98620133  1.01318309 -0.03289706  3.00847295 -1.02679092]
R-squared: 0.9259204134491424


In [12]:
#hypothesis testing on the coefficients

tester = LinearModelTester(model)
H0 = np.array([0,1,1,0,3,-1])
alpha = 0.05

# test H0 for each coefficient

results = tester.hypothesis_t_test(X, y, H0, alpha)
for result in results:
    print(f"Coefficient {result['coefficient']}:")
    print(f"  Estimated: {result['beta_estimate']}")
    print(f"  Null value: {result['null_value']}")
    print(f"  t-stat: {result['t_stat']}")
    print(f"  p-value: {result['p_value']}")
    print(f"  Reject null: {result['reject_null']}")

# build confidence intervals for coefficients
results = tester.confidence_interval(X, y, alpha)
for result in results:
    print('--'*40)
    print(f"Coefficient {result['coefficient']}:")
    print(f"  Estimated: {result['beta_estimate']}")
    print(f"  Confidence interval: [{result['confidence_lower']}, {result['confidence_upper']}]")

# hypothesis testing on linear combinations of coefficients
R = np.array([
    [0, 1, -1, 0, 0, 0],  # beta_1 - beta_2 = 0
    [0, 0, 2, 0, 0, 2]   # 2*beta_2 + 2*beta_5 = 0
])
r = [0, 0] 

# H0 = Rbeta = r

results = tester.hypothesis_F_test(X, y, R, r, alpha)
print('--'*40)
print(f"F-stat: {results['F_stat']}")
print(f"p-value: {results['p_value']}")
print(f"Reject null: {results['reject_null']}")



Coefficient 0:
  Estimated: -0.020956408714166208
  Null value: 0
  t-stat: -0.6704950528825446
  p-value: 0.5026980078679999
  Reject null: False
Coefficient 1:
  Estimated: 0.9862013324637019
  Null value: 1
  t-stat: -0.43719825879662916
  p-value: 0.6620625378445069
  Reject null: False
Coefficient 2:
  Estimated: 1.013183086563438
  Null value: 1
  t-stat: 0.3953575243015688
  p-value: 0.6926638823957914
  Reject null: False
Coefficient 3:
  Estimated: -0.0328970595911511
  Null value: 0
  t-stat: -1.060481138694913
  p-value: 0.28918337260347227
  Reject null: False
Coefficient 4:
  Estimated: 3.0084729523193987
  Null value: 3
  t-stat: 0.2723490663792494
  p-value: 0.7854101946438525
  Reject null: False
Coefficient 5:
  Estimated: -1.026790915553867
  Null value: -1
  t-stat: -0.8484471213816155
  p-value: 0.3963932771608605
  Reject null: False
--------------------------------------------------------------------------------
Coefficient 0:
  Estimated: -0.020956408714166208
  

In [13]:
alpha = 0.05
result = tester.prediction_interval_m(X, y, x_new, alpha)
print('--'*40)
print(f"Prediction interval for new point m{x_new}:")
print(f"  Estimated m(x_new): {result['mx_new_estimate']}")
print(f"  Confidence interval: [{result['confidence_lower']}, {result['confidence_upper']}]")

result = tester.prediction_interval_y(X, y, x_new, alpha)
print('--'*40)
print(f"Prediction interval for response of new point, y_new:")
print(f"  Confidence interval: [{result['confidence_lower']}, {result['confidence_upper']}]")


--------------------------------------------------------------------------------
Prediction interval for new point m[[ 2.04253623 -0.91946118  0.11467003 -0.1374237   1.36552692]]:
  Estimated m(x_new): -0.757505417301134
  Confidence interval: [-0.9397209890558961, -0.5752898455463719]
--------------------------------------------------------------------------------
Prediction interval for response of new point, y_new:
  Confidence interval: [-2.6998488506853864, 1.1848380160831187]
